export const ROLES = {
    ROLE_ADMIN:             'ROLE_ADMIN',

    ROLE_NEWS_CREATE:       'ROLE_NEWS_CREATE',
    ROLE_NEWS_VIEW:         'ROLE_NEWS_VIEW',
    ROLE_NEWS_EDIT:         'ROLE_NEWS_EDIT',
    ROLE_NEWS_DELETE:       'ROLE_NEWS_DELETE',
    ROLE_NEWS_APPROVE:      'ROLE_NEWS_APPROVE',

    ROLE_REPORT_VIEW:       'ROLE_REPORT_VIEW',
    ROLE_REPORT_PRINT:      'ROLE_REPORT_PRINT',
    ROLE_REPORT_EXPORT:     'ROLE_REPORT_EXPORT',

    ROLE_MNG_COMMON:        'ROLE_MNG_COMMON',
		ROLE_TOPIC_VIEW:        'ROLE_TOPIC_VIEW',
		ROLE_TOPIC_CREATE:      'ROLE_TOPIC_CREATE',
		ROLE_TOPIC_UPDATE:      'ROLE_TOPIC_UPDATE',
		ROLE_TOPIC_DELETE:      'ROLE_TOPIC_DELETE',

		ROLE_DEPARTMENT_VIEW:   'ROLE_DEPARTMENT_VIEW',
		ROLE_DEPARTMENT_CREATE: 'ROLE_DEPARTMENT_CREATE',
		ROLE_DEPARTMENT_UPDATE: 'ROLE_DEPARTMENT_UPDATE',
		ROLE_DEPARTMENT_DELETE: 'ROLE_DEPARTMENT_DELETE',
		
		ROLE_COMMENT_VIEW:      'ROLE_COMMENT_VIEW',
		ROLE_COMMENT_APPROVE:   'ROLE_COMMENT_APPROVE',
		ROLE_COMMENT_DELETE:    'ROLE_COMMENT_DELETE',

		ROLE_NEWTYPE_VIEW:      'ROLE_NEWTYPE_VIEW',
		ROLE_NEWTYPE_CREATE:	'ROLE_NEWTYPE_CREATE',
		ROLE_NEWTYPE_UPDATE:    'ROLE_NEWTYPE_UPDATE',


    ROLE_MNG_SYSTEM:        'ROLE_MNG_SYSTEM',
		ROLE_GROUP_USER_VIEW:   'ROLE_GROUP_USER_VIEW',
		ROLE_GROUP_USER_CREATE: 'ROLE_GROUP_USER_CREATE',
		ROLE_GROUP_USER_UPDATE: 'ROLE_GROUP_USER_UPDATE',
		ROLE_GROUP_USER_DELETE: 'ROLE_GROUP_USER_DELETE',

		ROLE_USER_VIEW:         'ROLE_USER_VIEW',
		ROLE_USER_CREATE:       'ROLE_USER_CREATE',
		ROLE_USER_UPDATE:       'ROLE_USER_UPDATE',
		ROLE_USER_DELETE:       'ROLE_USER_DELETE',
		ROLE_USER_SET_AUTHORITY:'ROLE_USER_SET_AUTHORITY',
		
		ROLE_SYS_PARAM_VIEW:    'ROLE_SYS_PARAM_VIEW',
		ROLE_SYS_PARAM_CREATE:  'ROLE_SYS_PARAM_CREATE',
		ROLE_SYS_PARAM_UPDATE:  'ROLE_SYS_PARAM_UPDATE',
		ROLE_NEWTYPE_VIEW:	   	'ROLE_NEWTYPE_VIEW',
};


