export const ROLES = {
    ROLE_ADMIN:             'ROLE_ADMIN',

    ROLE_REPORT_VIEW:       'ROLE_REPORT_VIEW',
    ROLE_REPORT_PRINT:      'ROLE_REPORT_PRINT',
    ROLE_REPORT_EXPORT:     'ROLE_REPORT_EXPORT',

    ROLE_MNG_COMMON:        'ROLE_MNG_COMMON',
		ROLE_MATERIAL_VIEW:        'ROLE_MATERIAL_VIEW',
		ROLE_MATERIAL_CREATE:      'ROLE_MATERIAL_CREATE',
		ROLE_MATERIAL_UPDATE:      'ROLE_MATERIAL_UPDATE',
		ROLE_MATERIAL_DELETE:      'ROLE_MATERIAL_DELETE',

		ROLE_MATERIAL_BATCH_VIEW:   'ROLE_MATERIAL_BATCH_VIEW',
		ROLE_MATERIAL_BATCH_CREATE: 'ROLE_MATERIAL_BATCH_CREATE',
		ROLE_MATERIAL_BATCH_UPDATE: 'ROLE_MATERIAL_BATCH_UPDATE',
		ROLE_MATERIAL_BATCH_DELETE: 'ROLE_MATERIAL_BATCH_DELETE',

		ROLE_MATERIAL_TYPE_VIEW:      'ROLE_MATERIAL_TYPE_VIEW',
		ROLE_MATERIAL_TYPE_CREATE:	'ROLE_MATERIAL_TYPE_CREATE',
		ROLE_MATERIAL_TYPE_UPDATE:    'ROLE_MATERIAL_TYPE_UPDATE',


    ROLE_MNG_SYSTEM:        'ROLE_MNG_SYSTEM',

		ROLE_USER_VIEW:         'ROLE_USER_VIEW',
		ROLE_USER_CREATE:       'ROLE_USER_CREATE',
		ROLE_USER_UPDATE:       'ROLE_USER_UPDATE',
		ROLE_USER_DELETE:       'ROLE_USER_DELETE',
		ROLE_USER_SET_AUTHORITY:'ROLE_USER_SET_AUTHORITY',
		
		ROLE_SYS_PARAM_VIEW:    'ROLE_SYS_PARAM_VIEW',
		ROLE_SYS_PARAM_CREATE:  'ROLE_SYS_PARAM_CREATE',
		ROLE_SYS_PARAM_UPDATE:  'ROLE_SYS_PARAM_UPDATE',
		ROLE_NEWTYPE_VIEW:	   	'ROLE_NEWTYPE_VIEW',
	
	ROLE_PATIENT_VIEW:	'ROLE_PATIENT_VIEW',
	ROLE_PATIENT_CREATE:	'ROLE_PATIENT_CREATE',
	ROLE_PATIENT_UPDATE:	'ROLE_PATIENT_UPDATE',

	ROLE_SESSION_VIEW:	'ROLE_SESSION_VIEW',
	ROLE_SESSION_CREATE:	'ROLE_SESSION_CREATE',
	ROLE_SESSION_UPDATE:	'ROLE_SESSION_UPDATE',
	ROLE_SESSION_DELETE:	'ROLE_SESSION_DELETE'
};


